# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pios < Formula
  desc "AI Project Execution Contract CLI"
  homepage "https://github.com/cclavin/PIOS"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Darwin_x86_64.tar.gz"
      sha256 "0eb7e330ef2b0ea7807dc99c999ceae61f1ab9102012aaa013db9d907e104421"

      define_method(:install) do
        bin.install "pios"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Darwin_arm64.tar.gz"
      sha256 "c22a0a2a9a8ea1af7ed9bceb555c82bbe8488c666aaf1106363e33bff01d4dca"

      define_method(:install) do
        bin.install "pios"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Linux_x86_64.tar.gz"
      sha256 "0b4cb8db5d48ee908acdfe2b69733b54799f4a9085bcc9ce1cad3f19fde918dd"
      define_method(:install) do
        bin.install "pios"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Linux_arm64.tar.gz"
      sha256 "d736317d146b4fd9bed52e8a981d5dbffd7f3b637d5f8f65be0fc411262df10d"
      define_method(:install) do
        bin.install "pios"
      end
    end
  end

  test do
    system "#{bin}/pios --help"
  end
end
