# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pios < Formula
  desc "AI Project Execution Contract CLI"
  homepage "https://github.com/cclavin/PIOS"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Darwin_x86_64.tar.gz"
      sha256 "8b2a5c98498eed9e41d500d0c5b2692d783444b4fd1972c12ed25704f93f67d3"

      define_method(:install) do
        bin.install "pios"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Darwin_arm64.tar.gz"
      sha256 "81fccaf399e60a7aa1f26b4e62a57752a0c8888b565a47c4aa0c3543c1005d82"

      define_method(:install) do
        bin.install "pios"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Linux_x86_64.tar.gz"
      sha256 "bda2d73dc00d7d100dadc41a7a1b299bf89b08cd5c6ec3d5ab00f7159d9c6357"
      define_method(:install) do
        bin.install "pios"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/cclavin/pios/releases/download/v1.0.0/pios_Linux_arm64.tar.gz"
      sha256 "dd395511dd418b3597c0124dc4788eacf46dca7cf12dd6883154525c7f58ad55"
      define_method(:install) do
        bin.install "pios"
      end
    end
  end

  test do
    system "#{bin}/pios --help"
  end
end
